### PR TITLE
Fix issue which caused Faraday to resolve to latest version.

### PR DESCRIPTION
**Pull request by pedelman**
- Update gemspec to fix Faraday gem version to point to latest patch
  version
- Update rubocop issues
- Support setting ssl options for OAuth API mode

### CODE REVIEW

**Comment by pedelman** [comment]
Fixes #141

**Comment by pedelman** [comment]
Please hold off on merge -- doing some more in depth testing.

**Comment by pedelman** [comment]
Okay this code seems to be running fine for me. Can someone else play with this to make sure?

You can pull down my branch then:

```
gem uninstall bigcommerce
bundle install
rake build
gem install pkg/bigcommerce-1.0.0.gem
```

Then I create a `.env-dev` file which has the following structure.

```
# You can get these values from the `Advanced Setttings > API Accounts` section on the Control Panel
export BC_API_ENDPOINT=https://api.bigcommerce.com
export BC_STORE_HASH=STORE_HASH
export BC_ACCESS_TOKEN=ACCESS_TOKEN
export BC_CLIENT_ID=CLIENT_ID
export BC_CLIENT_SECRET=CLIENT_SECRET
```

Source the ENV and make sure they are set up properly.

```
source .env-dev

echo $BC_API_ENDPOINT
https://api.bigcommerce.com
```

Now I can run:

```
ruby examples/content/blog_post.rb
```

**Comment by mattolson** [comment]
@pedelman Works for me!

**Pull request merged**
